name: Deploy web app to GH Pages

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Generate artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/

  deploy:
    name: Deploy artifact to GH Pages
    runs-on: ubuntu-latest
    needs: [build]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
